### ISSUE TITLE
Adição de compatibilidade para importação de arquivos CSV

### ISSUE THREAD

**Issue by VHChavesC** [VHChavesC/VHChavesC-DC-UFSCar-ES2-201902-GrupoVitorChaves#3]
> Na funcionalidade Importação de itens bibliográficos na base de dados atual (File -> Import into current library), oferecer a opção de importar arquivo em formato .CSV

**Comment by joao-coli** [comment]
Tudo indica que está ok. Em breve haverá o pull request.
